### ISSUE TITLE
Add City Searching to Location API

### ISSUE THREAD

**Issue by adamo57** [adamo57/grappos#1]
Currently, the user cannot search for wines by city name, they can only search for wines by postal code. 

We need to have the SearchForLocation func updated to take in a city name as well as a postal code.

API Docs for reference: https://www.grappos.com/api-setup/

**Comment by mattgd** [comment]
Are there any location strings that should remain invalid (e.g. less than five characters, but all digits), or should the `locationDataRetriever` be the only thing to handle validation from now on?

**Comment by adamo57** [comment]
Hey @mattgd, good question. I would leave the validation to the response coming back and have it say something like, "There aren't any wines at that location" if the response comes back as an empty array
